### ISSUE TITLE
TensorFlow 1.15 does not install

### ISSUE THREAD

**Issue by Expert73** [fo40225/tensorflow-windows-wheel#103]
wheel.py, line 463, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: tensorflow-gpu==1.15.0 .dist-info directory not found

**Comment by fo40225** [comment]
What is your install command?

**Comment by Expert73** [comment]
python.exe -m pip install tensorflow-1.15.0-cp37-cp37m-win_amd64.whl
from the second time it was installed without errors. It is possible, where the team made a mistake

**Comment by Expert73** [comment]
Thanks for great job!
