### ISSUE TITLE
CPP can only used on X64, when I switch toX86, error happend， anyone can tell me how to solve it?

### ISSUE THREAD

**Issue by perfectworld0415** [fo40225/tensorflow-windows-wheel#118]
I download  this package named:"libtensorflow-gpu-windows-x86_64-1.10.0-sse2cuda92cudnn72.7z"
It can only used on X64, when I switch to X86, Error happed. It shows like missing dll file.

**Comment by fo40225** [comment]
x86 and x64 has different binary.

You should use `libtensorflow-cpu-windows-x86_32-1.10.0-sse2.7z`.

**Comment by perfectworld0415** [comment]
@fo40225 
Did this package supply GPU acceleration？if not ,Will you supply a package with GPU acceleration on X86 in future? thk U for your reply

**Comment by fo40225** [comment]
cudnn didn't support 32bit OS, there is no way to build a 32bit lib with GPU support.

**Comment by perfectworld0415** [comment]
@fo40225 thk U very much!  live and learn
