### ISSUE TITLE
How to use tensorflow 1.10.0 CPP version in Visual Studio 2017

### ISSUE THREAD

**Issue by rioadhii** [fo40225/tensorflow-windows-wheel#138]
Hi, I need help, how do you use libtensorflow-gpu-windows-x86_64-1.10.0-sse2cuda92cudnn72.7z in visual studio 2017? like anything I have to configure to use this library in VS

I need to import this
#include "tensorflow/cc/client/client_session.h"
#include "tensorflow/cc/ops/standard_ops.h"
#include "tensorflow/core/framework/tensor.h"
#include "tensorflow/core/public/session.h"

to my CPP Project

OS: Windows 10
CUDA: 9.2.148
cuDNN: 7.2.1.38
Visual Studion: 2017 Community
Graphics : NVidia 920MX

I apologize if this is a basic question, before this, I tried building it from source, but it always _erorr selected compiler is not compatible with cuda_. Then I found this source. Thank you by the way

**Comment by fo40225** [comment]
https://github.com/fo40225/tensorflow-windows-wheel/issues/59#issuecomment-445444433
