### ISSUE TITLE
Python 3.6 wheel for GPU sse2 was not uploaded correctly

### ISSUE THREAD

**Issue by konstantinki** [fo40225/tensorflow-windows-wheel#14]
The file size tensorflow-windows-wheel/1.8.0/py36/GPU/cuda91cudnn71sse2/tensorflow_gpu-1.8.0-cp36-cp36m-win_amd64.whl is too small, can't be installed

**Comment by fo40225** [comment]
#13 

https://github.com/fo40225/tensorflow-windows-wheel/raw/master/1.8.0/py36/GPU/cuda91cudnn71sse2/tensorflow_gpu-1.8.0-cp36-cp36m-win_amd64.whl

**Comment by konstantinki** [comment]
ok, I was able to install the package, but after import it looks empty:
```
import tensorflow as tf
dir(tf)
```
['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__']
File is about 45 Mb

**Comment by konstantinki** [comment]
thanks, it works now.
