### ISSUE TITLE
why there dont have libtensorflow-cpu-windows-x86_32-1.8.0-avx2.7z? just have libtensorflow-cpu-windows-x86_64-1.8.0-avx2.7z

### ISSUE THREAD

**Issue by JaosonMa** [fo40225/tensorflow-windows-wheel#145]
i want use tf .dll in c++ vs, i can run succ with libtensorflow-cpu-windows-x86_64-1.8.0-avx2.7z, but it is x64, my project is x86 , so i want use it in x86 project ? can you complie the libtensorflow-cpu-windows-x86_32-1.8.0-avx2.7z ?
我的工程师32位的，所以64位的没办法使用，可以编译一个 avx2的32位 dll吗？

我用 了 32位的 libtensorflow-cpu-windows-x86_32-1.8.0-sse2,但是 提示报错Your CPU supports instructions that this TensorFlow binary was not compiled to use：AVX AVX2

![image](https://user-images.githubusercontent.com/23551774/83614503-da66f480-a5b7-11ea-8d8c-4a66e89a2bde.png)

**Comment by JaosonMa** [comment]
@fo40225  can you help me with this problem?

**Comment by fo40225** [comment]
`Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2` is an information message, not error.

**Comment by JaosonMa** [comment]
> `Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2` is an information message, not error.

c++ code [https://github.com/zhangcliff/tensorflow-c-mnist/blob/master/tf.cpp](url)
i google this , it is not error, but with the debug ,it can not run succ,  debug result:
![image](https://user-images.githubusercontent.com/23551774/83616067-f66b9580-a5b9-11ea-89d2-db2045251f5c.png)

release resoult:
![image](https://user-images.githubusercontent.com/23551774/83616045-eeabf100-a5b9-11ea-895f-bd279f1e1c6a.png)

i can not debug the code  with debug ,  how can i slove this ?  does it have the code like python 
#import os.
#os.environ["TF_CPP_MIN_LOG_LEVEL"] = '2'
to jump this waring ,to run succ with debug?
and i also wander will it be faster then sse2 if i can use the avx2 ,

**Comment by fo40225** [comment]
The libtensorflow is release build.

I have never successfully built a debug version.

You can use `_putenv_s` to set environment variables.

**Comment by JaosonMa** [comment]
> The libtensorflow is release build.
> 
> I have never successfully built a debug version.
> 
> You can use `_putenv_s` to set environment variables.

i got what you mean，but i dont know the environment var's name , i google this but nothing was helpful, do you know ?
and can you tell me will you comlile libtensorflow-cpu-windows-x86_32-1.8.0-avx2.7z , best wishes to you !

**Comment by fo40225** [comment]
`TF_CPP_MIN_LOG_LEVEL` is the environment variable's name.

Just use sse2 for maximum compatibility.

**Comment by JaosonMa** [comment]
> TF_CPP_MIN_LOG_LEVEL

1、i got the log level
![image](https://user-images.githubusercontent.com/23551774/83622274-50705900-a5c2-11ea-89d8-b442de805465.png)
2、add int res = _putenv("TF_CPP_MIN_LOG_LEVEL=3") 
nothing changed. 
it always error in 
![image](https://user-images.githubusercontent.com/23551774/83622762-ff149980-a5c2-11ea-954e-ff64ec45b934.png)
![image](https://user-images.githubusercontent.com/23551774/83622816-118ed300-a5c3-11ea-9e23-f0df599c61cf.png)

**Comment by fo40225** [comment]
I can't confirm if https://github.com/zhangcliff/tensorflow-c-mnist/blob/master/tf.cpp compatible with tf 1.8.

You can try this 
https://github.com/tensorflow/tensorflow/blob/v1.8.0/tensorflow/cc/tutorials/example_trainer.cc

**Comment by JaosonMa** [comment]
> I can't confirm if https://github.com/zhangcliff/tensorflow-c-mnist/blob/master/tf.cpp compatible with tf 1.8.
> 
> You can try this
> https://github.com/tensorflow/tensorflow/blob/v1.8.0/tensorflow/cc/tutorials/example_trainer.cc

i will try it, thanks a lot!
c++  cpu use tensorflow is not a good choice!!!
