### ISSUE TITLE
cudnn 7.1.3 for windows unavailable

### ISSUE THREAD

**Issue by GLJeff** [fo40225/tensorflow-windows-wheel#15]
Got /1.8.0/py36/GPU/cuda91cudnn71avx2  but there simply are no windows version of 7.1.X available from nvidia that work with cuda91...

**Comment by fo40225** [comment]
download archive here https://github.com/fo40225/tensorflow-windows-wheel/issues/12#issuecomment-390462502

or use cuda92cudnn71sse2 instead

**Comment by GLJeff** [comment]
ty

**Comment by DenisDollfus** [comment]
Hi @fo40225, similar issue here, I've installed cuda91cudnn71sse2 and I'm now stuck looking for cudnn 7.1 for windows 7...

**Comment by fo40225** [comment]
@DenisDollfus sorry I don't have cudnn win7 backup file.

**Comment by DenisDollfus** [comment]
@fo40225  Thanks anyway for your builds, very useful for those like me who have a (relatively) old CPU but great (upgraded) GPU and want to use TensorFlow.
Do you know by chance if cudnn for win10 could work on win7?

**Comment by fo40225** [comment]
@DenisDollfus You can try it and feedback to here.

**Comment by DenisDollfus** [comment]
So far cuDNN 7.1.3 for CUDA 9.1 Windows 10 works fine on Windows 7, at least for my use cases, simple convolutional NN.
