### ISSUE TITLE
unable to install tensorflow 1.5 python 2.7 sse2

### ISSUE THREAD

**Issue by Adamszk** [fo40225/tensorflow-windows-wheel#150]
This is a very useful site.
I tried to install tensorflow in my virtual environment (venv):

pip install https://github.com/fo40225/tensorflow-windows-wheel/tree/master/1.5.0/py27/CPU/sse2/tensorflow-1.5.0-cp27-cp27m-win_amd64.whl

but I am getting error messages (BadZipFile: File is not a zip file).

I also tried,

pip install https://raw.github.com/fo40225/tensorflow-windows-wheel/tree/master/1.5.0/py27/CPU/sse2/tensorflow-1.5.0-cp27-cp27m-win_amd64.whl
 
still error messages with https address error.

Is my approach correct?  
May I suggest that you provide a little more information on how to install a package.

**Comment by fo40225** [comment]
Use bowser open the link https://github.com/fo40225/tensorflow-windows-wheel/tree/master/1.5.0/py27/CPU/sse2/tensorflow-1.5.0-cp27-cp27m-win_amd64.whl, press the download button to download the whl file.

**Comment by Adamszk** [comment]
where do I place that whl file in virtual environment called env2 so that pip can see it?

**Comment by Adamszk** [comment]
Never mind, I figure it out.   It will be located in temp where env folder is or temp/env.
Thanks for assistance.  This git is very useful. It addresses the issues with the need for older versions.
