### ISSUE TITLE
Prebuilt wheel with CUDNN 8 support (either via CUDA 10.2 or 11.0 support)

### ISSUE THREAD

**Issue by oscarbg** [fo40225/tensorflow-windows-wheel#151]

**Comment by fo40225** [comment]
It is hard to build tf 2.2.0 with cuda 11 & cudnn 8, just wait for tf 2.3.0.

**Comment by oscarbg** [comment]
ok will wait.. but seems Tensorflow isn’t building 2.3 with CUDA11 & CUDNN 8 by default and seems coming in Tensorflow 2.4.. 
will you be able to provide an rc1 build to not have to wait some months for final 2.3?
thanks..

**Comment by fo40225** [comment]
The master branch can be built with cuda 11 & cudnn8, tf2.3 should also work.

I'm trying to cherry-pick some commit to 2.2.0 to build with cuda 11, but there is no good news yet.

**Comment by oscarbg** [comment]
thanks for trying..
being me wouldn't take the effort to backport changes.. 
seems tensorflow 2.3 is branching next week so an early build from this branch would be good enough for testing while waiting for a stable release..

**Comment by fo40225** [comment]
https://github.com/fo40225/tensorflow-windows-wheel/tree/master/2.2.0/py38/CPU%2BGPU/cuda110cudnn8sse2

tensorflow 2.2.0 + some code fix
cuda 11 rc (cuda_11.0.1_451.22)
cudnn 8 (cudnn-11.0-v8.0.0.180)
python 3.8.0
msvc 2019 16.6
No-AVX

For testing purposes only, no guarantee.

**Comment by oscarbg** [comment]
thanks ! 
 &works nice on first try..
