### ISSUE TITLE
Cuda 11 cuDNN 8

### ISSUE THREAD

**Issue by Expert73** [fo40225/tensorflow-windows-wheel#156]
how did you solve the problem with the thust module during the build?

when i try to build i have some problem:
#error The version of CUB in your include path is not compatible with this release of Thrust. CUB is now included in the CUDA Toolkit, so you no longer need to use your own checkout of CUB. Define THRUST_IGNORE_CUB_VERSION_CHECK to ignore this.

**Comment by fo40225** [comment]
```
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified:
/DTHRUST_IGNORE_CUB_VERSION_CHECK
```

**Comment by Expert73** [comment]
I don't understand what the command line will look like.
now:
bazel --output_base=c:/bazel/output_dir/ build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package

**Comment by Expert73** [comment]
I think TF 2.3 not work with cudnn 8 (final). 
if you can make the build share the secret of how you did it.

**Comment by fo40225** [comment]
I can build tf 2.3.0 with cuda11+cudnn8 without modification.

**Comment by Expert73** [comment]
thanks! I try it again. Maybe my problem in mkl.
I build versions 2.1 and 2.2 with double optimizations. The performance was higher
