### ISSUE TITLE
[Pre-Built Wheel Request] Tensorflow 2.2 No GPU No AVX

### ISSUE THREAD

**Issue by Monster-Gaming-Studios** [fo40225/tensorflow-windows-wheel#159]
As the title says, can you please give a pre-built wheel for Tensorflow 2.2 with no GPU and no AVX. I know 2.2 wheel is there but it has GPU support. I don't have GPU, so I need one with only CPU and without AVX(only with SSE).

Thanks in advance.

**Comment by fo40225** [comment]
When CUDA is not installed, the CPU will be used.

**Comment by Monster-Gaming-Studios** [comment]
Ok. Thanks.
