### ISSUE TITLE
Tensorflow for Java with GPU support

### ISSUE THREAD

**Issue by Neiko2002** [fo40225/tensorflow-windows-wheel#16]
Great Repository. I was wondering if you can share the build process in the github wiki. Other than that it would be nice if you can add java bindings to Tensorflow-GPU. This is something Google does not provide.

**Comment by fo40225** [comment]
I use cmake to build tensorflow currently, and it didn't support build C api or JNI binding.

Google use bazel to build official C library and Java support, they are working on the building tensorflow 
gpu support with bazel on windows.

**Comment by Neiko2002** [comment]
Thanks for letting me know.
