### ISSUE TITLE
Possibility of specifying configure file to build.

### ISSUE THREAD

**Issue by MegaPanchamZ** [fo40225/tensorflow-windows-wheel#161]
I'm asking this so that I can know exactly what settings are needed in the ./configure file so that users can build the pip package themselves. After following googles build from source instructions, It became apparent that the configuration settings for building are very vague.

Is it possible to explain the configure file and put it in the readme or inside the repo what settings were used specifically to build the wheel?

Thanks

**Comment by fo40225** [comment]
https://www.tensorflow.org/install/source_windows#expandable-1

**Comment by MegaPanchamZ** [comment]
Are those settings accurate to what you use to build without AVX instructions?

**Comment by fo40225** [comment]
https://github.com/fo40225/tensorflow-windows-wheel/issues/128#issuecomment-595645185

**Comment by MegaPanchamZ** [comment]
Does that mean I just have to do a vanilla build command like bazel build..... With no options?

**Comment by fo40225** [comment]
https://www.tensorflow.org/install/source_windows#gpu_support

No special parameters are required.

No need to modify the source code.

**Comment by MegaPanchamZ** [comment]
So, to put it simply I just need to run Bazel build? and this will build a package with no AVX and GPU support?

**Comment by fo40225** [comment]
Prepare the build environment according to the instructions of official documents.

Answer `/nologo` if you don't need AVX when asked for optimization parameters.

`bazel build --config=opt --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package` to build the source code.

`bazel-bin\tensorflow\tools\pip_package\build_pip_package C:/tmp/tensorflow_pkg` to generate whl file to C:\tmp\tensorflow_pkg

**Comment by MegaPanchamZ** [comment]
@fo40225  Thanks, I'll run the build today and see if it works. Do you want the wheel later to include in the repo?

**Comment by sonfire86** [comment]
@MegaPanchamZ version bazel?

**Comment by MegaPanchamZ** [comment]
Bazel Version 3.5.0

**Comment by sonfire86** [comment]
@MegaPanchamZ I tried bazel 3.1.0 and 3.5.0, it`s bad. My error 
`ERROR: G:/tensorflow/tensorflow/core/grappler/BUILD:168:1: C++ compilation of rule '//tensorflow/core/grappler:grappler_item_builder' failed (Exit 2): python.exe failed: error executing command`
`Target //tensorflow/tools/pip_package:build_pip_package failed to build`

**Comment by MegaPanchamZ** [comment]
@fo40225 quick question, in the build command what does `--define=no_tensorflow_py_deps=true` mean?
