### ISSUE TITLE
Support for AVX512

### ISSUE THREAD

**Issue by jacano** [fo40225/tensorflow-windows-wheel#17]
Hi guys, do you have any plan to add Tensorflow binaries with AVX512 support?
Thanks for such a great work @fo40225!

**Comment by fo40225** [comment]
You can use Intel compiler and use /QxCORE-AVX512 to build a AVX512 supported tensorflow.

I don't have a CPU that support avx512, I can't help you.

**Comment by jacano** [comment]
Thanks anyway, keep up the good work!
