### ISSUE TITLE
Linux binaries

### ISSUE THREAD

**Issue by loretoparisi** [fo40225/tensorflow-windows-wheel#170]
Thank you for this project, it's a great effort!
Any plan to provide linux binaries for older cpus (no avx etc.) or any guidance for that?

Thanks a lot!

**Comment by fo40225** [comment]
https://github.com/davidenunes/tensorflow-wheels
https://github.com/yaroslavvb/tensorflow-community-wheels/issues
https://www.tensorflow.org/install/source
