### ISSUE TITLE
ERROR: tensorflow_gpu-1.8.0-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform

### ISSUE THREAD

**Issue by irtizashabrez** [fo40225/tensorflow-windows-wheel#174]
Hello,

I am trying to install tensorflow_gpu-1.8.0-cp36-cp36m-win_amd64.whl.
I have:
i7 3770K
GTX 670
Windows 10 version 19042.867
Anaconda 64bit version 4.9.2

I created two different environments with
1. conda create -n gpuv1 python=3.5 (installed 3.5.6)
2. conda create -n gpuv2 python=3.5.2 --channel conda-forge

On both environments, tensorflow 1.8.0 fails to install with following error:

ERROR: tensorflow_gpu-1.8.0-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform

I looked at issues and also searched on google but can not figure out what is wrong with my setup. I have 64bit anaconda and 64bit windows. Your help is appreciated. Thanks.

**Comment by fo40225** [comment]
tensorflow_gpu-1.8.0-cp36-cp36m-win_amd64.whl needs python 3.6.

**Comment by irtizashabrez** [comment]
Thanks
