### ISSUE TITLE
Python 3.8 & Compute Capability 3.0

### ISSUE THREAD

**Issue by MrP123** [fo40225/tensorflow-windows-wheel#176]
Hello!

I'm looking for a wheel of TF for Python 3.8 that is compiled for a CUDA compute capability of 3.0 under Windows x86_64.
Is something like this available, or can I simply use the "2.2.0\py37\CPU+GPU\cuda102cudnn76sse2" wheel?

 I'd appreciate any help I can get.

Thanks!

**Comment by fo40225** [comment]
Do you have any issues that you can't use python 3.7?

**Comment by MrP123** [comment]
I'm using a proprietary library for interfacing to a machine vision camera that only supports python 3.8.
