### ISSUE TITLE
help for 1.15.5 

### ISSUE THREAD

**Issue by ssbuild** [fo40225/tensorflow-windows-wheel#184]
when i build win nvida/tensorflow for 1.15.5  meet lot of linking error  , could you privide window src patch for  tensorflow-windows-wheel/1.15.4+nv20.12/ .

**Comment by fo40225** [comment]
https://github.com/NVIDIA/tensorflow/pull/14/files

**Comment by ssbuild** [comment]
> https://github.com/NVIDIA/tensorflow/pull/14/files

**Comment by ssbuild** [comment]
> https://github.com/NVIDIA/tensorflow/pull/14/files

libtraining_ops.lo(training_ops.o) : error LNK2019: 无法解析的外部符号 "public: void __cdecl tensorflow::functor::ApplyPowerSign<struct Eigen::GpuDevice,struct Eigen::half>::operator()(struct Eigen::GpuDevice const &,class Eigen::TensorMap<class Eigen::Tensor<struct Eigen::half,1,1,__int64>,16,struct Eigen::MakePointer>,class Eigen::TensorMap<class Eigen::Tensor<struct Eigen::half,1,1,__int64>,16,struct Eigen::MakePointer>,class Eigen::TensorMap<class Eigen::TensorFixedSize<struct Eigen::half const ,struct Eigen::Sizes<>,1,__int64>,16,struct Eigen::MakePointer>,class Eigen::TensorMap<class Eigen::TensorFixedSize<struct Eigen::half const ,struct Eigen::Sizes<>,1,__int64>,16,struct Eigen::MakePointer>,class Eigen::TensorMap<class Eigen::TensorFixedSize<struct Eigen::half const ,struct Eigen::Sizes<>,1,__int64>,16,struct Eigen::MakePointer>,class Eigen::TensorMap<class Eigen::TensorFixedSize<struct Eigen::half const ,struct Eigen::Sizes<>,1,__int64>,16,struct Eigen::MakePointer>,class Eigen::TensorMap<class Eigen::Tensor<struct Eigen::half const ,1,1,__int64>,16,struct Eigen::MakePointer>)" (??R?$ApplyPowerSign@UGpuDevice@Eigen@@Uhalf@2@@functor@tensorflow@@QEAAXAEBUGpuDevice@Eigen@@V?$TensorMap@V?$Tensor@Uhalf@Eigen@@$00$00_J@Eigen@@$0BA@UMakePointer@2@@4@1V?$TensorMap@V?$TensorFixedSize@$$CBUhalf@Eigen@@U?$Sizes@$S@2@$00_J@Eigen@@$0BA@UMakePointer@2@@4@222V?$TensorMap@V?$Tensor@$$CBUhalf@Eigen@@$00$00_J@Eigen@@$0BA@UMakePointer@2@@4@@Z)，函数 "public: virtual void __cdecl tensorflow::ApplyPowerSignOp<struct Eigen::GpuDevice,struct Eigen::half>::Compute(class tensorflow::OpKernelContext *)" (?Compute@?$ApplyPowerSignOp@UGpuDevice@Eigen@@Uhalf@2@@tensorflow@@UEAAXPEAVOpKernelContext@2@@Z)  中引用了该符号
libtraining_ops.lo(training_ops.o) : error LNK2019: 无法解析的外部符号 "public: void __cdecl tensorflow::functor::ApplyPowerSign<struct Eigen::GpuDevice,float>::operator()(struct Eigen::GpuDevice const &,class Eigen::TensorMap<class Eigen::Tensor<float,1,1,__int64>,16,struct Eigen::MakePointer>,class Eigen::TensorMap<class Eigen::Tensor<float,1,1,__int64>,16,struct Eigen::MakePointer>,class Eigen::TensorMap<class Eigen::TensorFixedSize<float const ,struct Eigen::Sizes<>,1,__int64>,16,struct Eigen::MakePointer>,class Eigen::TensorMap<class Eigen::TensorFixedSize<float const ,struct Eigen::Sizes<>,1,__int64>,16,struct Eigen::MakePointer>,class Eigen::TensorMap<class Eigen::TensorFixedSize<float const ,struct Eigen::Sizes<>,1,__int64>,16,struct Eigen::MakePointer>,class Eigen::TensorMap<class Eigen::TensorFixedSize<float const ,struct Eigen::Sizes<>,1,__int64>,16,struct Eigen::MakePointer>,class Eigen::TensorMap<class Eigen::Tensor<float const ,1,1,__int64>,16,struct Eigen::MakePointer>)" (??R?$ApplyPowerSign@UGpuDevice@Eigen@@M@functor@tensorflow@@QEAAXAEBUGpuDevice@Eigen@@V?$TensorMap@V?$Tensor@M$00$00_J@Eigen@@$0BA@UMakePointer@2@@4@1V?$TensorMap@V?$TensorFixedSize@$$CBMU?$Sizes@$S@Eigen@@$00_J@Eigen@@$0BA@UMakePointer@2@@4@222V?$TensorMap@V?$Tensor@$$CBM$00$00_J@Eigen@@$0BA@UMakePointer@2@@4@@Z)，函数 "public: virtual void __cdecl tensorflow::ApplyPowerSignOp<struct Eigen::GpuDevice,float>::Compute(class tensorflow::OpKernelContext *)" (?Compute@?$ApplyPowerSignOp@UGpuDevice@Eigen@@M@tensorflow@@UEAAXPEAVOpKernelContext@2@@Z) 中引用 了该符号
libtraining_ops.lo(training_ops.o) : error LNK2019: 无法解析的外部符号 "public: void __cdecl tensorflow::functor::ApplyPowerSign<struct Eigen::GpuDevice,double>::operator()(struct Eigen::GpuDevice const &,class Eigen::TensorMap<class Eigen::Tensor<double,1,1,__int64>,16,struct Eigen::MakePointer>,class Eigen::TensorMap<class Eigen::Tensor<double,1,1,__int64>,16,struct Eigen::MakePointer>,class Eigen::TensorMap<class Eigen::TensorFixedSize<double const ,struct Eigen::Sizes<>,1,__int64>,16,struct Eigen::MakePointer>,class Eigen::TensorMap<class Eigen::TensorFixedSize<double const ,struct Eigen::Sizes<>,1,__int64>,16,struct Eigen::MakePointer>,class Eigen::TensorMap<class Eigen::TensorFixedSize<double const ,struct Eigen::Sizes<>,1,__int64>,16,struct Eigen::MakePointer>,class Eigen::TensorMap<class Eigen::TensorFixedSize<double const ,struct Eigen::Sizes<>,1,__int64>,16,struct Eigen::MakePointer>,class Eigen::TensorMap<class Eigen::Tensor<double const ,1,1,__int64>,16,struct Eigen::MakePointer>)" (??R?$ApplyPowerSign@UGpuDevice@Eigen@@N@functor@tensorflow@@QEAAXAEBUGpuDevice@Eigen@@V?$TensorMap@V?$Tensor@N$00$00_J@Eigen@@$0BA@UMakePointer@2@@4@1V?$TensorMap@V?$TensorFixedSize@$$CBNU?$Sizes@$S@Eigen@@$00_J@Eigen@@$0BA@UMakePointer@2@@4@222V?$TensorMap@V?$Tensor@$$CBN$00$00_J@Eigen@@$0BA@UMakePointer@2@@4@@Z)，函数 "public: virtual void __cdecl tensorflow::ApplyPowerSignOp<struct Eigen::GpuDevice,double>::Compute(class tensorflow::OpKernelContext *)" (?Compute@?$ApplyPowerSignOp@UGpuDevice@Eigen@@N@tensorflow@@UEAAXPEAVOpKernelContext@2@@Z) 中引用了该符号
bazel-out\x64_windows-opt\bin\tensorflow\python\_pywrap_tensorflow_internal.so : fatal error LNK1120: 4076 个无法解析的外部命令
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 66.055s, Critical Path: 37.45s

**Comment by ssbuild** [comment]
lots of link error , this is Eigen not right version or what you think ? @fo40225

**Comment by fo40225** [comment]
`git clone https://github.com/fo40225/tensorflow-nvidia -b r1.15.4+nv20.12-win`

Can you build this branch?

If you are trying to port those commits to newer version, make sure to keep the newer eigen lib version.

**Comment by ssbuild** [comment]
> `git clone https://github.com/fo40225/tensorflow-nvidia -b r1.15.4+nv20.12-win`
> 
> Can you build this branch?
> 
> If you are trying to port those commits to newer version, make sure to keep the newer eigen lib version.

I update error messages, can you see what is going wrong, or any idea to solve it. @fo40225
