### ISSUE TITLE
Tensorflow 1.7.1 

### ISSUE THREAD

**Issue by AppyFizz911** [fo40225/tensorflow-windows-wheel#19]
Can you please compile TensorFlow 1.7.1 (GPU - CUDA 9.2 & CPU) as I need that specific version for a project ?

**Comment by fo40225** [comment]
Do you have any reason that you must to use 1.7.1 instead of 1.7.0?

1.7.1 seems like a minor change.

**Comment by AppyFizz911** [comment]
Apparently Unity Engine's new Machine learning uses Tensorflow 1.7.1 specifically..

**Comment by fo40225** [comment]
OK, I will update later.

Which one is you need first? (CPU GPU py2 py3 cpp sse2 avx2 cuda9.0 or 9.2)

**Comment by AppyFizz911** [comment]
Thanks! Take your time, It would be great to get CPU py3 avx2 (and GPU CUDA 9.2 later maybe ?)

**Comment by fo40225** [comment]
CPU: https://github.com/fo40225/tensorflow-windows-wheel/tree/master/1.7.1

GPU: 1.7.1 build break with cuda 9.2. Error msg is `error : initialnot allowed for __shared__ variable`.

**Comment by fo40225** [comment]
https://github.com/fo40225/tensorflow-windows-wheel/tree/master/1.7.1

**Comment by AppyFizz911** [comment]
Thanks
