### ISSUE TITLE
Not a supported wheel on this platform for python 3.6 builds

### ISSUE THREAD

**Issue by JulienSiems** [fo40225/tensorflow-windows-wheel#2]
Hi thanks for all the optimized builds!
Your python 2.7 builds for tf 1.5 all worked like a charm (both cpu and gpu) for me, but I run into problems when using python 3.6 builds. 

I create a new conda environment using
`conda create -n py36tf python=3.6`
and then attempt to install tensorflow
`pip install tensorflow_gpu-1.5.0-cp36-cp36m-win_amd64.whl`
but I get a not supported wheel error. 
I am on Windows 7 64 bit.

Possibly it's because of the precise python 3.6.x version you used?

Best, 
Julien

**Comment by fo40225** [comment]
Do you have executed `activate py36tf` command to activate your py36 env?

A clean install Anaconda3 4.4.0 should work well.

**Comment by szymko1995** [comment]
Works well on py36 and anaconda 5.0.1 for me.

**Comment by JulienSiems** [comment]
Sorry for not getting back to you earlier! I couldn't figure out why it didn't work, but it worked fine after setting up a new env so all good now!
