### ISSUE TITLE
tensorflow_gpu-1.8.0-cp27-cp27m-win_amd64.whl is not a support wheel on this platform

### ISSUE THREAD

**Issue by buaanie** [fo40225/tensorflow-windows-wheel#26]
OS: ubuntu 16.04
Python: 2.7
cuda: 9.2
cudnn: 7.1
this error info is given when i install your compiled whl file,pls help to check if the file is not complete?

**Comment by sleeplessai** [comment]
@buaanie 
for ubuntu pre-built tensorflow u can visit repo at https://github.com/mind/wheels

**Comment by tgbamg** [comment]
@buaanie This is a windows wheel.

**Comment by sleeplessai** [comment]
@buaanie 
you are welcome.
any issue else or close this one.
