### ISSUE TITLE
Microsoft C++ exception: std::length_error at memory location 0x0000001FA38FD0E0.

### ISSUE THREAD

**Issue by marcomanno** [fo40225/tensorflow-windows-wheel#29]
Hi All,
I am getting an std::length_error doing any operation, for example:
  tensorflow::ops::RandomNormal val(scope, { 3., 3. }, tensorflow::DT_FLOAT);

Do you have any advice? My PC does not have cuda.

**Comment by fo40225** [comment]
Can you provide more detail like environment or code?

**Comment by marcomanno** [comment]
Environment:
![image](https://user-images.githubusercontent.com/19752588/42734715-bbda1e3e-8840-11e8-9d58-f1046247d9b3.png)

**Comment by feifeizuo** [comment]
Does you use Debug model?

**Comment by marcomanno** [comment]
I have changed the package and stopped using the debug config.
Now everything is working.
