### ISSUE TITLE
TF 1.10 GPU SSE2 not compatible with Anaconda x64

### ISSUE THREAD

**Issue by fsergeyal** [fo40225/tensorflow-windows-wheel#41]
https://github.com/fo40225/tensorflow-windows-wheel/tree/master/1.10.0/py36/GPU/cuda92cudnn72sse2
Error says this wheels are not compatible with platform.

Seems it need Anaconda x86 platform

**Comment by fo40225** [comment]
Please don't change the filename.

**Comment by fsergeyal** [comment]
It's not obvious, but works. Thanks.
