### ISSUE TITLE
Build Steps for building c++ dll and libs on windows

### ISSUE THREAD

**Issue by AyushP123** [fo40225/tensorflow-windows-wheel#42]
Hi,
       Thanks a lot for sharing all the dlls and libs for windows. I wanted to know build steps that you used for building tensorflow c++ dlls and libs for windows 10 with tensorflow version 1.10, cuda 9.2 and cudnn 7.2.

**Comment by fo40225** [comment]
run vs2017 x64 native tools commands command prompt as admin

```
cmake .. -G "Visual Studio 15 2017" -A x64 -T host=x64 ^
-DCMAKE_BUILD_TYPE=Release ^
-DSWIG_EXECUTABLE=C:\Users\User\swigwin-3.0.10\swig.exe ^
-Dtensorflow_BUILD_CC_EXAMPLE=OFF ^
-Dtensorflow_BUILD_SHARED_LIB=ON ^
-Dtensorflow_ENABLE_GPU=ON ^
-Dtensorflow_CUDA_VERSION=9.2 ^
-DCUDA_HOST_COMPILER="C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.15.26726\bin\Hostx64\x64" 

cmake --build . --target INSTALL --config Release -- /m /fileLogger
```

result in `C:\Program Files (x86)\tensorflow`

and you should use tf 1.8, because https://github.com/fo40225/tensorflow-windows-wheel/issues/30

**Comment by AyushP123** [comment]
Is visual studio 2017 preferred or visual studio 2015 will also do??

**Comment by fo40225** [comment]
vs2015 or vs2017 is ok

**Comment by AyushP123** [comment]
Hi,
      Thanks a lot for your response. Can you also point me to an example for usage of the dll and lib using the header files to load and run inference.
