### ISSUE TITLE
TensorFlow 1.11 CPU x64 with AVX instructions ?

### ISSUE THREAD

**Issue by castillo92** [fo40225/tensorflow-windows-wheel#46]
Hello!

I used a lot of time 1.05 version with AVX compatibility, but it's time to upgrade

Please, can you compile the last version for the x64 AVX instruction? I only see AVX2

EDIT: I'm asking for Python 3.6 or 3.7, I dont care

**Comment by fo40225** [comment]
@castillo92 the official pip package after 1.6.0 is AVX built

**Comment by castillo92** [comment]
@fo40225 oh it's true! there aren't warnings in the console

Thanks you very much. I didn't read it in the official documentation

Regards!
