### ISSUE TITLE
source code

### ISSUE THREAD

**Issue by Kadantte** [fo40225/tensorflow-windows-wheel#53]
Hi, can u plz tell me how to build tensorflow as u do for SSE CPU's but i don't know how to edited to Support this Arch ... i want to build one for working on linux...

**Comment by fo40225** [comment]
I think you should change this option
```
Please specify optimization flags to use during compilation when bazel option "--config=opt"
is specified [Default is -march=native]:
```

Use `-march=native` or just press enter will fit your local CPU.

Use `-march=x86-64` can build a wheel that can run on all x86-64 CPU

You can find other flags in [GCC manual](https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html)

**Comment by Kadantte** [comment]
Thank you very much.
