### ISSUE TITLE
cuDNN 7.4 support

### ISSUE THREAD

**Issue by juliusfrost** [fo40225/tensorflow-windows-wheel#54]
Can you build with cuDNN 7.4, cuda 10 with python 3.7, 3.6?

**Comment by fo40225** [comment]
Just use cudnn 7.4.1's dll, it is compatible.

I will use newest cudnn when next tensorflow update released.

**Comment by port513** [comment]
I also would like 7.4.1 support
Tried to compile TensorFlow myself and I tried for 3 days before I found this site, thanks for saving my day ;)
