### ISSUE TITLE
Issue with running tensorflow cpp releases

### ISSUE THREAD

**Issue by HackersSpirit** [fo40225/tensorflow-windows-wheel#59]
Hello,
OS: Windows 10 64-bit
I tried to run the tensorflow program with different versions of tensorflow and getting the similar error all the time:
class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl tensorflow::Status::ToString(void)const " (?ToString@Status@tensorflow@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) referenced in function main
main.obj : error LNK2019: unresolved external symbol "public: virtual __cdecl tensorflow::ConfigProto::~ConfigProto(void)" (??1ConfigProto@tensorflow@@UEAA@XZ) referenced in function "public: __cdecl tensorflow::SessionOptions::~SessionOptions(void)" (??1SessionOptions@tensorflow@@QEAA@XZ)
main.obj : error LNK2019: unresolved external symbol "public: __cdecl tensorflow::SessionOptions::SessionOptions(void)" (??0SessionOptions@tensorflow@@QEAA@XZ) referenced in function main
main.obj : error LNK2019: unresolved external symbol "class tensorflow::Status __cdecl tensorflow::NewSession(struct tensorflow::SessionOptions const &,class tensorflow::Session * *)" (?NewSession@tensorflow@@YA?AVStatus@1@AEBUSessionOptions@1@PEAPEAVSession@1@@Z) referenced in function main
debug\tensorflowcppNew.exe : fatal error LNK1120: 4 unresolved externals
All the versions give me a linking error:
Please find the sample code that i am trying to run:
Session* session;
Status status = NewSession(SessionOptions(), &session);
```
if (!status.ok()) {
     std::cout << status.ToString() << "\n";
     return 1;
    }
``
```

**Comment by fo40225** [comment]
You can use Release build instead of Debug build to see if it resolve this error or not.

**Comment by HackersSpirit** [comment]
@fo40225 : Exactly which one is the release build. I downloaded suppose tensorflow 1.8 in lib folder i can see tensorflow.lib and tensorflow_static.lib
And there is tensorflow.dll file in the bin folder.
Sharing the program and the error message for clarity:
**Program:**
```
#define NOMINMAX
#include <Windows.h>
#include <QCoreApplication>
#include "tensorflow/core/public/session.h"
#include "tensorflow/core/platform/env.h"
#include "tensorflow/cc/client/client_session.h"

using namespace tensorflow;

int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);
    Session* session;
     Status status = NewSession(SessionOptions(), &session);
     if (!status.ok()) {
       std::cout << status.ToString() << "\n";
       return 1;
     }

    // Scope root = Scope::NewRootScope();

    return a.exec();
}
```
**Error Message:**
ain.obj : error LNK2019: unresolved external symbol "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl tensorflow::Status::ToString(void)const " (?ToString@Status@tensorflow@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) referenced in function main
main.obj : error LNK2019: unresolved external symbol "public: virtual __cdecl tensorflow::ConfigProto::~ConfigProto(void)" (??1ConfigProto@tensorflow@@UEAA@XZ) referenced in function "public: __cdecl tensorflow::SessionOptions::~SessionOptions(void)" (??1SessionOptions@tensorflow@@QEAA@XZ)
main.obj : error LNK2019: unresolved external symbol "public: __cdecl tensorflow::SessionOptions::SessionOptions(void)" (??0SessionOptions@tensorflow@@QEAA@XZ) referenced in function main
main.obj : error LNK2019: unresolved external symbol "class tensorflow::Status __cdecl tensorflow::NewSession(struct tensorflow::SessionOptions const &,class tensorflow::Session * *)" (?NewSession@tensorflow@@YA?AVStatus@1@AEBUSessionOptions@1@PEAPEAVSession@1@@Z) referenced in function main
debug\tensorflowcppNew.exe : fatal error LNK1120: 4 unresolved externals

**Comment by fo40225** [comment]
Try to link protobuf 3.4.1 lib in your project

**Comment by HackersSpirit** [comment]
Do I have to download and build it.
Because i tried to link protobuf.lib file which i got through bazel build and it is giving me 
the same error condition

**Comment by HackersSpirit** [comment]
@fo40225 : Actually i am getting symbol not found issue in the library. It is similar to the issue faced in the libtensorflow_cc.so generated by bazel which is an ongoing issue in the forum. 
Can you please try to run the sample program on prebuilt libary of tensorflow 1.8  or can you please tell the  exact steps which you are following so that i can replicate.
I am stuck in the issue for long time.

**Comment by fo40225** [comment]
https://youtu.be/7u3tE1lqmbw

**Comment by fo40225** [comment]
https://youtu.be/aoIS-wuoPdg

Can't reproduce your error.

**Comment by HackersSpirit** [comment]
@fo40225 : Just making myself clear. 
Actually the above message :  Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
Does not appear as error message. It just gets displayed on the command line when i run the library build using sse2.

**Comment by HackersSpirit** [comment]
> https://youtu.be/7u3tE1lqmbw

@fo40225 : Just for clarification.
Are all the builds are in release mode ?
Asking this because i am getting a lot of difference in performace.
For Ex. Python takes 55 ms to predicts whereas cpp release takes about 500ms
In the video you have selected multiple lines using mouse and aligned them, how to do that? ;p

**Comment by fo40225** [comment]
@HackersSpirit all build is Release built (in fact, tensorflow will build break in debug mode)

press ALT + mouse or arrow key to do column selection (vertical selection, block selection whatever) in most code editor (even in Word)

**Comment by HackersSpirit** [comment]
@fo40225 : thanks 
Lol about ALT + mouse i was trying shift mouse and ctrl mouse.
And do you have any idea why there is difference in performance of the library files
