### ISSUE TITLE
TensorFlow 1.10 with Cuda9.2.148 cuDNN 7. 2.1 Python2.7

### ISSUE THREAD

**Issue by wenwenyu** [fo40225/tensorflow-windows-wheel#62]
Hi, I installed tensorflow_gpu-1.10.0-cp27-cp27m-win_amd64.whl that you provided, but when I used tensorflow  then my program got errors. The error message is that 'module' object has no attribute xxxx. .Why?

**Comment by fo40225** [comment]
You should post the full error message and simplest code that can cause error.

**Comment by wenwenyu** [comment]
Thank you for your reply. my simplest code as follows:
```
import tensorflow as tf 
a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
c = tf.matmul(a, b)
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
print sess.run(c)
```
then error message as follows:
```
Traceback (most recent call last):
  File "C:/Users/user/PycharmProjects/untitled/testgpu.py", line 2, in <module>
    a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
AttributeError: 'module' object has no attribute 'constant'
```

**Comment by wenwenyu** [comment]
I found that no matter what tensorflow's api I called then I would  get an error message as  'module' object has no attribute 'xxxxx'.

**Comment by fo40225** [comment]
Try to use tf 1.9, 1.10 also broken on my py27 env

**Comment by wenwenyu** [comment]
Hi. I use tf 1.9 than it works. Thanks!

**Comment by wenwenyu** [comment]
OK. I will try to test it and reply to you as soon as possibly.

**Comment by wenwenyu** [comment]
@fo40225 Hi,I have tested it and it works!
