### ISSUE TITLE
sharing some tf 1.12.0 builds

### ISSUE THREAD

**Issue by iperov** [fo40225/tensorflow-windows-wheel#73]
I am using tf 1.12.0 for my DeepFaceLab project, because tf 1.13.1 has OOM issue https://github.com/tensorflow/tensorflow/issues/26218

for python 3.6

tensorflow-r1.12_cuda_9.2_7.5.0_3.5_SSE :
https://mega.nz/#!WksH0Kib!zKB8OIjFKLt374C8S4bT1YBsl83eyNlOBR65b01grjI

tensorflow-r1.12_cuda_10.1_7.5.0_3.5_AVX
https://mega.nz/#!6l0lkSYA!zYV9Max6Pkr5a3pOi5Za9d1ghz1xFR8D2hGbcJkvc2k

if you want, download them and add to your repo, I will delete it in one week.

**Comment by fo40225** [comment]
You can create a repo and upload the file to release, it makes the file keep on Github forever.

Maybe someone who needs those file will find it.

**Comment by iperov** [comment]
if you don't need them, me too

**Comment by l2009312042** [comment]
i need  cuda10   cudnn7.5  python3.6  tensorflow    but  it   has been deleted

**Comment by iperov** [comment]
@l2009312042 because I author of this repo dont need them, so I deleted them, because my mega.nz free space is limited
