### ISSUE TITLE
help with change GPU compute capability

### ISSUE THREAD

**Issue by swxs** [fo40225/tensorflow-windows-wheel#88]
Configuration used:
Python 3.7
AVX2 (/arch:AVX2)
CUDA Toolkit 10.1
cuDNN v7.3.1
**GPU compute capability 6.1**

the current version need a Minimum 7.0

**Comment by fo40225** [comment]
@swxs 
Which whl file did you installed?

**Comment by swxs** [comment]
1.13.1/py37
GPU/avx2/TensorCore
tensorflow_gpu-1.13.1+nv-cp37-cp37m-win_amd64.7z.001
tensorflow_gpu-1.13.1+nv-cp37-cp37m-win_amd64.7z.002

**Comment by fo40225** [comment]
@swxs 
Only compute capability 7.0 and up have TensorCore.

The file target to use fp16 TensorCore acceleration need compute capability 7.0.

**Comment by swxs** [comment]
ok, tks!
