### ISSUE TITLE
TFLite missing from contrib

### ISSUE THREAD

**Issue by vijaysaimutyala** [fo40225/tensorflow-windows-wheel#9]
Thanks for the wheel and am able to use 1.7 on my Windows 10 machine. I have a question though. I'm working on models to be implemented in an Android app. I observe that TFLite is missing from contrib and am not able to use TFLite associated commands like **toco**. 

Does this mean that processor that does not support AVX are barred from using TFLite ?

**Comment by fo40225** [comment]
Tensorflow Lite has not supported Windows yet.

You may want to check this [PR](https://github.com/tensorflow/tensorflow/pull/16490)

**Comment by fo40225** [comment]
It's possible to build tensorflow lite on windows by MSYS2 env.

Step:

- Download and install [MSYS2](https://www.msys2.org)

`http://repo.msys2.org/distrib/i686/msys2-i686-20161025.exe`

- Update package manager

open MSYS2 MSYS and execute
``` shell
pacman -Syuu
````
and follow the instructions.

- Install toolchain
``` shell
pacman -S base libraries compression VCS sys-utils net-utils base-devel msys2-devel mingw-w64-i686-toolchain mingw-w64-x86_64-toolchain development --needed
```

- Get tensorflow lite source and apply some necessary patch.
``` shell
git clone https://github.com/tensorflow/tensorflow.git -b tflite-v0.1.7
cd tensorflow
git cherry-pick -m 1 3128b4
git cherry-pick bc86da
./tensorflow/contrib/lite/download_dependencies.sh
```

- Build
```shell
make -f tensorflow/contrib/lite/Makefile
```

FInally, you will get `tensorflow/contrib/lite/gen/bin/minimal.exe` that depands on `MSYS-2.0.DLL, MSYS-GCC_S-SEH-1.DLL, MSYS-STDC++-6.DLL`, and `tensorflow/contrib/lite/gen/lib/libtensorflow-lite.a` is static lib.
