### ISSUE TITLE
logging.h编译时报错

### ISSUE THREAD

**Issue by jun20061588** [fo40225/tensorflow-windows-wheel#90]
您好，我用libtensorflow-gpu-windows-x86_64-1.9.0-avx2cuda92cudnn71进行编译，编译过程中，在logging.h 229 TF_DEFINE_CHECK_OP_IMPL(Check_EQ, ==) 报错，报错：严重性	
错误	C2589	“(”:“::”右边的非法标记	Project1	e:\libtensorflow-gpu-windows-x86_64-1.9.0-sse2cuda92cudnn71\include\tensorflow\core\platform\default\logging.h	229

**Comment by fo40225** [comment]
@jun20061588 

https://github.com/tensorflow/tensorflow/issues/22646

**Comment by jun20061588** [comment]
非常感谢，已经成功运行了
